# Generated by Django 3.0.1 on 2020-01-01 12:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Manager Name')),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skillset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField(verbose_name='Mobile Number')),
                ('pan', models.CharField(max_length=15, verbose_name='PAN Number')),
                ('date_joined', models.DateField(default=datetime.date.today, verbose_name='date of joining')),
            ],
        ),
        migrations.CreateModel(
            name='KRA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_achieve', models.CharField(max_length=200)),
                ('tag_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perform.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Start Date')),
                ('due_date', models.DateField(default=datetime.date.today, verbose_name='Due date')),
                ('goal_name', models.CharField(max_length=100, verbose_name='Goal Name')),
                ('priority', models.CharField(choices=[(0, 'Low Priority'), (1, 'Medium Priority'), (2, 'High Priority'), (3, 'Highest Priority'), (4, 'No Priority')], default=1, max_length=10)),
                ('desciption', models.TextField()),
                ('progress', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[(0, 'Pending'), (1, 'Completed'), (2, 'Overdue'), (3, 'Delayed')], max_length=20)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perform.Managers')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perform.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_area', models.TextField(verbose_name='Feedback')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perform.Staff')),
            ],
        ),
    ]
