# Generated by Django 3.0.1 on 2020-01-04 09:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_Cateog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(choices=[(0, 'Reporting To'), (1, 'Peer-To-Peer'), (2, '360-Degree')], default=0, max_length=20)),
                ('categories', models.ManyToManyField(related_name='Categories', to='perform.Feedback_Cateog')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Job Name')),
                ('hours', models.IntegerField()),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_skill', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('select_skill', models.ManyToManyField(related_name='Skills', to='perform.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='TagKra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightage', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Skillset',
        ),
        migrations.RenameField(
            model_name='kra',
            old_name='to_achieve',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='kra',
            name='tag_to',
        ),
        migrations.AddField(
            model_name='kra',
            name='desciption',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='goals',
            name='progress',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='tagkra',
            name='kra_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perform.KRA'),
        ),
        migrations.AddField(
            model_name='goals',
            name='associate_job',
            field=models.ManyToManyField(blank=True, to='perform.Job'),
        ),
    ]
