# Generated by Django 3.0.1 on 2020-01-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perform', '0003_auto_20200104_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perform.Feedback_Cateog'),
        ),
    ]
